service: cloudwatch-alarm-to-slack

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${file(share/terraform/terraform.json):aws_region}
  memorySize: 128
  environment:
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}

plugins:
  - serverless-plugin-include-dependencies

package:
  exclude:
    - node_modules/**
    - .serverless/**
    - serverless.yml
    - .git/**
    - .gitignore
    - .idea/**
    - '*.iml'
    - test/**
    - package.json
    - .babelrc
    - .eslintignore
    - .eslintrc
    - README.md
    - src/**
    - coverage/**

functions:
  handler:
    handler: lib/index.handler
    events:
      - sns: ${file(share/terraform/terraform.json):aws_sns_topic_arn}

resources:
  Resources:
    HandlerLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 30
